from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession
from app.database import get_db
from pydantic import BaseModel
from typing import List

router = APIRouter()

class AgentResponse(BaseModel):
    id: str
    name: str
    description: str
    status: str

@router.get("/", response_model=List[AgentResponse])
async def list_agents(db: AsyncSession = Depends(get_db)):
    """
    List all available agents
    """
    return []

@router.get("/{agent_id}", response_model=AgentResponse)
async def get_agent(agent_id: str, db: AsyncSession = Depends(get_db)):
    """
    Get agent details
    """
    return {"id": agent_id, "name": "Agent", "description": "Description", "status": "online"}

@router.get("/{agent_id}/signals")
async def get_agent_signals(agent_id: str, db: AsyncSession = Depends(get_db)):
    """
    Get signals generated by an agent
    """
    return []